# On Splunk indexer (SIEM): /opt/splunk/etc/system/local/inputs.conf
# Enable receiving (also via UI)

[splunktcp://9997]
disabled = 0

# Optional syslog from Linux target
[tcp://1514]
connection_host = ip
index = linux
sourcetype = syslog
disabled = 1
