# Place on Splunk Universal Forwarder (Windows):
# C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf

[default]
host = soc-victim

[WinEventLog://Security]
disabled = 0
index = windows
renderXml = 0

[WinEventLog://System]
disabled = 0
index = windows

[WinEventLog://Application]
disabled = 0
index = windows

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = sysmon
renderXml = 0

# Optional: monitor a lab folder for dropped scripts
[monitor://C:\Users\labuser\Desktop\soc-lab-exfil]
disabled = 0
index = windows
sourcetype = soc_lab_exfil
